### ISSUE TITLE
Simplify testnet account table

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex-web#192]
I feel information could be more condensed or that part of it could be removed and put in "View details".

@mikera What kind of informations do you feel should absolutely figure in this table?

Main motivation is that even on desktop I get an X scrollbar (similarly to #191 ):

![Screenshot from 2021-09-11 11-24-04](https://user-images.githubusercontent.com/17478152/132943175-76c1b501-ec56-4dbc-9941-e05f415d7bd9.png)

**Comment by mikera** [comment]
This strikes me as a layout problem first and foremost. 
- The "Signer" Column could be much smaller (Should also probably be called "Account".
- "View" is unnecessary  since the block is already a link.
- "Timestamp" -> "Time"

The table can also use more of the screen, there is no point leaving whitespace to the right. Can use 100% I think?
